spring:
  application:
    name: "api-gateway-3"

server:
  port: 4003

management:
  security:
    enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka,http://localhost:3002/eureka,http://localhost:3003/eureka