spring:
  application:
    name: eureka-server-2

server:
  port: 3002

management:
  security:
    enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka,http://localhost:3003/eureka