spring:
  application:
    name: eureka-server-1

server:
  port: 3001

management:
  security:
    enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:3002/eureka,http://localhost:3003/eureka