spring:
  application:
    name: "hello-service-1"

hello:
  message: "Hello Prod1 Message!"

server:
  port: 5001

management:
  security:
    enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:3001/eureka,http://localhost:3002/eureka,http://localhost:3003/eureka